language: go
go:
  - 1.x

addons:
  apt:
    packages:
    - xz-utils

sudo: required
services:
  - docker

env:
  - GOVERSION=1.12

install: true

cache:
  directories:
    - ~/.cache

script:
   - docker build -t fonero-project/fnodata .
   - ./run_tests.sh docker
